### ISSUE TITLE
Instructions Request

### ISSUE THREAD

**Issue by Amadeus-** [ketho-wow/MuteAnnoying-Converter#1]
Ketho,

If it's not too much trouble, could you provide some basic instructions in your readme.md?  I would like to be able to do the powershell and lua scripts you created on my own custom "Sounds" directory.

It doesn't have to be extensive -- but, just pointing in the right directory would be fantastic.

Also, AWESOME job on the new addon ...it's exactly what I was looking for!

**Comment by Ketho** [comment]
Thanks 😄
I tried to give some directions now but I'm kind of new to stuff outside of wow addons
